version: "3.7"
# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  caddy:
    image: caddy:latest
    # https://hub.docker.com/_/caddy
    volumes:
      - bookstack_public:/var/www/bookstack/public
      - caddy_data:/data
      - ./bookstack_caddyfile:/etc/caddy/Caddyfile
    networks:
      - bookstack
    ports:
      # CHANGE TO "80:80" IF USING CADDY FOR HTTPS
      - "9080:80"
      # UNCOMMENT IF USING CADDY FOR HTTPS
      # - "443:443"
    environment:
      # https://caddyserver.com/docs/automatic-https#overview
      - DOMAIN=:80

  mariadb:
    image: mariadb:latest
    # https://hub.docker.com/_/mariadb
    volumes:
      - bookstack_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGEME
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=CHANGEME
    networks:
      - bookstack_db

  bookstack:
    image: zeigren/bookstack:latest # ghcr.io/zeigren/bookstack_docker:latest
    # https://hub.docker.com/r/zeigren/bookstack
    environment:
      - DB_HOST=mariadb:3306
      - DB_PASSWORD=CHANGEME
      - APP_URL=https://bookstack.yourdomain.test
      # Can be 'local', 'local_secure' or 's3'
      - STORAGE_TYPE=local
      - REDIS_SERVERS=redis:6379:0
    volumes:
      - bookstack_storage:/var/www/bookstack/storage
      - bookstack_public:/var/www/bookstack/public
    depends_on:
      - mariadb
    networks:
      - bookstack
      - bookstack_db

  redis:
    image: redis:alpine
    # https://hub.docker.com/_/redis
    networks:
      - bookstack

volumes:
  bookstack_db:
  bookstack_storage:
  bookstack_public:
  caddy_data:

networks:
  bookstack:
  bookstack_db:
