version: "3.8"
# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  caddy:
    image: caddy:latest
    # https://hub.docker.com/_/caddy
    volumes:
      - bookstack_public:/var/www/bookstack/public
      - caddy_data:/data
    networks:
      - bookstack
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: bookstack_caddyfile
        target: /etc/caddy/Caddyfile
    environment:
      # https://caddyserver.com/docs/automatic-https#overview
      - DOMAIN=bookstack.yourdomain.test

  mariadb:
    image: mariadb:latest
    # https://hub.docker.com/_/mariadb
    volumes:
      - bookstack_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/bookstacksql_password
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD_FILE=/run/secrets/bookstacksql_password
    secrets:
      - bookstacksql_password
    networks:
      - bookstack_db

  bookstack:
    image: zeigren/bookstack:latest # ghcr.io/zeigren/bookstack_docker:latest
    # https://hub.docker.com/r/zeigren/bookstack
    environment:
      - DB_PASSWORD=DOCKER-SECRET->bookstacksql_password
      - APP_URL=https://bookstack.yourdomain.test
      # Can be 'local', 'local_secure' or 's3'
      - STORAGE_TYPE=local
      # Run first without APP_KEY to have the container create one
      # - APP_KEY=DOCKER-SECRET->bookstack_app_key
    volumes:
      - bookstack_storage:/var/www/bookstack/storage
      - bookstack_public:/var/www/bookstack/public
    networks:
      - bookstack
      - bookstack_db
      - redis
    secrets:
      - bookstacksql_password
      - bookstack_app_key

  redis:
    image: redis:alpine
    # https://hub.docker.com/_/redis
    networks:
      - redis

volumes:
  bookstack_db:
  bookstack_storage:
  bookstack_public:
  caddy_data:

secrets:
  bookstacksql_password:
    external: true
  bookstack_app_key:
    external: true

networks:
  bookstack:
  bookstack_db:
  redis:

configs:
  bookstack_caddyfile:
    external: true
