version: '3.7'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - bookstack_public:/var/www/bookstack/public
    depends_on:
      - bookstack
    networks:
      - bookstack
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: bookstack_vhost
        target: /etc/nginx/conf.d/default.conf
    secrets:
      - source: yourdomain.com.crt
        target: /etc/nginx/certs/yourdomain.com.crt
      - source: yourdomain.com.key
        target: /etc/nginx/certs/yourdomain.com.key
      - source: dhparam.pem
        target: /etc/nginx/dhparam/dhparam.pem

  mariadb:
    image: mariadb:latest
    volumes:
      - bookstack_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/bookstacksql_root_password
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD_FILE=/run/secrets/bookstacksql_password
# work around for https://github.com/docker-library/mariadb/issues/262
      - MYSQL_INITDB_SKIP_TZINFO=1
    secrets:
      - bookstacksql_root_password
      - bookstacksql_password
    networks:
      - bookstack_db

  bookstack:
    image: zeigren/bookstack:latest
    depends_on:
    - mariadb
    environment:
#   BookStack Settings
    - DB_HOST=mariadb:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=DOCKER-SECRET->bookstacksql_password
    - APP_URL=https://bookstack.yourdomain.com
    - CACHE_DRIVER=redis
    - SESSION_DRIVER=redis
    - STORAGE_TYPE=local
    - STORAGE_IMAGE_TYPE=local
    - STORAGE_ATTACHMENT_TYPE=local_secure
    - REDIS_SERVERS=redis:6379:0
    volumes:
    - bookstack_storage:/var/www/bookstack/storage
    - bookstack_public_storage:/var/www/bookstack/public/storage
    - bookstack_public:/var/www/bookstack/public
    networks:
    - bookstack
    - bookstack_db
    secrets:
      - bookstacksql_password

  redis:
    image: redis:alpine
    networks:
      - bookstack

volumes:
  bookstack_db:
  bookstack_storage:
  bookstack_public_storage:
  bookstack_public:

secrets:
  bookstacksql_root_password:
    external: true
  bookstacksql_password:
    external: true
  yourdomain.com.crt:
    external: true
  yourdomain.com.key:
    external: true
  dhparam.pem:
    external: true

networks:
  bookstack:
  bookstack_db:

configs:
  bookstack_vhost:
    external: true
