version: '3.7'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - bookstack_public:/var/www/bookstack/public
      - ./config/test_vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bookstack
    networks:
      - bookstack
    ports:
      - "9080:80"

  mariadb:
    image: mariadb:latest
    volumes:
      - bookstack_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGEME
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=CHANGEME
# work around for https://github.com/docker-library/mariadb/issues/262
      - MYSQL_INITDB_SKIP_TZINFO=1
    networks:
      - bookstack_db

  bookstack:
    image: zeigren/bookstack:latest
    depends_on:
    - mariadb
    environment:
#   BookStack Settings
    - DB_HOST=mariadb:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=CHANGEME
    - APP_URL=null
    - CACHE_DRIVER=redis
    - SESSION_DRIVER=redis
    - REDIS_SERVERS=redis:6379:0
    - STORAGE_TYPE=local
    volumes:
    - bookstack_storage:/var/www/bookstack/storage
    - bookstack_public:/var/www/bookstack/public
    networks:
    - bookstack
    - bookstack_db

  redis:
    image: redis:alpine
    networks:
      - bookstack

volumes:
  bookstack_db:
  bookstack_storage:
  bookstack_public_storage:
  bookstack_public:

networks:
  bookstack:
  bookstack_db:
